export const EXCHAGNE_BOOL = "EXCHAGNE_BOOL";
export const ADD_TODO = "ADDED";
export const ONE_SELECT = "ONE_SELECT";
export const UPDATE = "UPDATAE";
export const DELETE = "DELECTE";
export const FETCH_TODOS_REQUEST = "FETCH_TODOS_REQUEST";
export const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS";
export const FETCH_TODOS_FAILURE = "FETCH_TODOS_FAILURE";
